markdown: kramdown
permalink: /story/:title.html

<<<<<<< Updated upstream
url: www.example.com # update this to your site url: eg www.example.com
baseurl: '' # if needed: eg /test
=======
baseurl: '/ext/dmag'
>>>>>>> Stashed changes

description: Site description here
exclude: [".gitignore", "README.md", "Gemfile", "Gemfile.lock"]


# default meta for index page
meta:
  description: "Meta description for index page"
  keywords: "one1, two2, three3"
  author: "John Doe"
