markdown: kramdown
permalink: /blog/:title
paginate: 4
paginate_path: /blog/page:num

url: ''
baseurl: ''

description: Site description here

gems: [jekyll-paginate]
exclude: [".gitignore", "README.md", "Gemfile", "Gemfile.lock"]
