markdown: kramdown
permalink: /blog/:title.html

baseurl: /gg

description: Site description here
exclude: [".gitignore", "README.md", "Gemfile", "Gemfile.lock"]


# default meta for index page
meta:
  description: "Meta description for index page"
  keywords: "one1, two2, three3"
  author: "John Doe"
