markdown: kramdown
permalink: /blog/:title.html
future: true # display future posts

<<<<<<< HEAD
url: http://gorilla-digital.de # your site url: eg www.example.com without / at the end
baseurl: '/ext/dev/armag' # if needed: eg /test
imgbase: '/ext/dev/armag/img/' # images folder: eg /test/img/
=======
url: https://railsr.github.io # your site url: eg www.example.com without / at the end
baseurl: '/gg' # if needed: eg /test
imgbase: '/gg/img/' # images folder: eg /test/img/
>>>>>>> gh-pages

facebook:
  app_id: 1592384934401140 # facebook app id for sharing

# default meta for index page
meta:
  description: "Meta description for index page"
  keywords: "one1, two2, three3"
  author: "John Doe"

description: Site description here
exclude: [".gitignore", "README.md", "Gemfile", "Gemfile.lock"]
