markdown: kramdown
permalink: /blog/:title.html
future: true # display future posts

url: http://example.com # your site url: eg www.example.com without / at the end
baseurl: '' # if needed: eg /test
imgbase: '/img/' # images folder: eg /test/img

facebook:
  app_id: 310388269340473 # facebook app id for sharing

# default meta for index page
meta:
  description: "Meta description for index page"
  keywords: "one1, two2, three3"
  author: "John Doe"

description: Site description here
exclude: [".gitignore", "README.md", "Gemfile", "Gemfile.lock"]
